export const GET_RELATED_ITEMS_DATA = 'GET_RELATED_ITEMS_DATA';
export const GET_RAW_CONTENT = 'GET_RAW_CONTENT';
export const GET_FOLDERISH_CONTENT = 'GET_FOLDERISH_CONTENT';
export const GET_SITE_TITLE = 'GET_SITE_TITLE';
