version: '3.8'

services:
    plone:
        build:
            context: ../plone-5
        volumes:
            - plone-data:/data:z
        networks:
            - cogs_proxy
        restart: always

    volto-v1:
        build:
            context: ../volto
        environment:
            - RAZZLE_API_PATH=https://climate-1.ukstats.dev/api
            - NODE_ENV=production
            - VIRTUAL_HOST=climate-1.ukstats.dev
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=climate-1.ukstats.dev
            - ADDONS="@eeacms/volto-plotlycharts;@eeacms/volto-datablocks;@eeacms/volto-columns-block;volto-slate:asDefault;volto-authomatic;volto-govuk-theme;volto-chart-builder"
        command: "yarn start:prod"
        init: true
        networks:
            - cogs_proxy
        restart: always

    volto-v2:
        build:
            context: ../volto
        environment:
            - RAZZLE_API_PATH=https://climate-2.ukstats.dev/api
            - NODE_ENV=production
            - VIRTUAL_HOST=climate-2.ukstats.dev
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=climate-2.ukstats.dev
            - ADDONS="@eeacms/volto-plotlycharts;@eeacms/volto-datablocks;@eeacms/volto-columns-block;volto-slate:asDefault;volto-authomatic;volto-govuk-theme;volto-chart-builder;volto-climatechange-elements"
        command: "yarn start:prod"
        init: true
        networks:
            - cogs_proxy
        restart: always

volumes:
    plone-data:

networks:
    cogs_proxy:
        external: true
