version: '3.8'

services:
    plone-vawag:
        image: plone-vawag:${GIT_COMMIT_SHORT}
        build:
            context: ../plone-5
        volumes:
            - vawag-data:/data:z
        networks:
            - cogs_proxy
        restart: always

    plone-cc2:
        image: plone-cc2:${GIT_COMMIT_SHORT}
        build:
            context: ../plone-5
        volumes:
            - cc2-data:/data:z
        networks:
            - cogs_proxy
        restart: always

    volto-vawag:
        image: volto-vawag:${GIT_COMMIT_SHORT}
        build:
            context: ../volto
            args:
                ADDONS: "@eeacms/volto-datablocks;@eeacms/volto-columns-block;volto-slate:asDefault;volto-authomatic;volto-govuk-theme;volto-chart-builder"
        environment:
            - RAZZLE_API_PATH=https://vawg.ukstats.dev/api
            - NODE_ENV=production
            - VIRTUAL_HOST=vawg.ukstats.dev
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=vawg.ukstats.dev
        command: "yarn start:prod"
        init: true
        networks:
            - cogs_proxy
        restart: always

    volto-v2:
        image: volto-v2:${GIT_COMMIT_SHORT}
        build:
            context: ../volto
            args:
                ADDONS: "@eeacms/volto-datablocks;@eeacms/volto-columns-block;volto-slate:asDefault;volto-authomatic;volto-govuk-theme;volto-chart-builder;volto-climatechange-elements"
        environment:
            - RAZZLE_API_PATH=https://staging.climate-change.data.gov.uk/api
            - RAZZLE_GA4_CODE=G-Y84VSLC1LC
            - HOTJAR_ID=3118262
            - HOTJAR_VERSION=6
            - NODE_ENV=production
            - VIRTUAL_HOST=staging.climate-change.data.gov.uk
            - VIRTUAL_PORT=3000
            - LETSENCRYPT_HOST=staging.climate-change.data.gov.uk
        command: "yarn start:prod"
        init: true
        networks:
            - cogs_proxy
        restart: always

volumes:
    vawag-data:
    cc2-data:

networks:
    cogs_proxy:
        external: true
