name: Build
on:
  create:
    tags:
       - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  docker_build_push:
    env:
      GIT_REF: ${{ github.ref }}
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: |
        docker-compose pull plone
        docker-compose pull volto
    - name: Push Volto
      run: |
        vers_num="$(grep 'version :=' build.sbt | head -n1 | sed 's/.*"\(.*\)".*/\1/')"
        
        rel_cand_substring='rc'
        vers_num_lower_case=${vers_num,,}
        
        local_param="volto:$vers_num"
        remote_param="gsscogs/volto"
        push_param="$remote_param:v$vers_num"
        latest_param="$remote_param:latest"
        
        docker tag $local_param $push_param
        if [[ "$vers_num_lower_case" != *"$rel_cand_substring"* ]]
          then docker tag $push_param $latest_param
        fi
        docker image push --all-tags $remote_param
    - name: Push Plone
      run: |
        vers_num="$(grep 'version :=' build.sbt | head -n1 | sed 's/.*"\(.*\)".*/\1/')"
        
        rel_cand_substring='rc'
        vers_num_lower_case=${vers_num,,}
        
        local_param="plone:$vers_num"
        remote_param="gsscogs/plone"
        push_param="$remote_param:v$vers_num"
        latest_param="$remote_param:latest"
        
        docker tag $local_param $push_param
        if [[ "$vers_num_lower_case" != *"$rel_cand_substring"* ]]
          then docker tag $push_param $latest_param
        fi
        docker image push --all-tags $remote_param